### ISSUE TITLE
ERROR START SERVER WEBSITE

### ISSUE THREAD

**Issue by heisty** [facebook/react-native-website#278]
ERROR: No 'original_id' field found in .../version-0.10/modal.md.Perhaps you forgot.....

can't start server why?

**Comment by charpeni** [comment]
Both of you are on Windows?

**Comment by ronaldroe** [comment]
Here's the full error:

```
E:\docs\react-native-website\website>npm start

> react-native-website@0.0.1 start E:\docs\react-native-website\website
> docusaurus-start

Starting Docusaurus server on port 3000...
No 'original_id' field found in E:/docs/react-native-website/website/versioned_docs/version-0.10/modal.md. Perhaps you forgot to add it when importing prior versions of your docs?
E:\docs\react-native-website\website\node_modules\docusaurus\lib\start-server.js:70
        throw ex;
        ^

Error: No 'original_id' field found in E:/docs/react-native-website/website/versioned_docs/version-0.10/modal.md. Perhaps you forgot to add it when importing prior versions of your docs?
    at E:/docs/react-native-website/website/node_modules/docusaurus/lib/server/versionFallback.js:104:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:/docs/react-native-website/website/node_modules/docusaurus/lib/server/versionFallback.js:92:7)
    at Module._compile (module.js:635:30)
    at loader (E:\docs\react-native-website\website\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\docs\react-native-website\website\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-website@0.0.1 start: `docusaurus-start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-website@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ronal\AppData\Roaming\npm-cache\_logs\2018-05-05T12_36_06_007Z-debug.log
```

**Comment by endiliey** [comment]
Hi @ronaldroe @heisty 

I am a contributor of Docusaurus, I can see that this error is due to markdown header being parsed incorrectly as being empty, and some error is thrown later on because of that.

Can you try to re-clone the repo, bump your docusaurus version in `website/package.json` to the latest version 
```
"dependencies": {
    "docusaurus": "^1.1.5",
},
```
Then`yarn install` and see if you can start the server ? (`yarn start`)

I believe https://github.com/facebook/Docusaurus/pull/583 might fix this.
If this is fixed, the more reason to bump Docusaurus version to the latest one. #382
If it is not fixed, we might need to file an issue at https://github.com/facebook/Docusaurus/
