### ISSUE TITLE
Add note to Android envitonment setup for React Native Cli on MacOS

### ISSUE THREAD

**Issue by VladRDV** [facebook/react-native-website#2994]
## Description

I was trying to setup the latest latest RN environment version on my mac, I've followed the official 0.67 version guide to the letter
but when running: `sdkmanager "platforms;android-30" "system-images;android-30;default;x86_64" "system-images;android-30;google_apis;x86" &&
sdkmanager "cmdline-tools;latest" "build-tools;30.0.2"`

I kept getting this exeption:

``` 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
    at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
    at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
    at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
    at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
    at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 5 more
```

## Solution

The only solution proposed online, that ended up working was described in this [Reddit post](https://www.reddit.com/r/androiddev/comments/snn2be/comment/hw3g129/?utm_source=share&utm_medium=web2x&context=3)

The problem is that with PATH setup from [official docs](https://reactnative.dev/docs/environment-setup) for 0.67(latest version at the time of this issue creation) at least on Mac we end up with `sdkmanager` command addresssing the wrong folder in Android SDK. `sdkmanager` refers to `/bin/sdkmanager` inside `/tools`, while the correct folder is `/cmdline-tools`

After I applied author's solution from this post (big thanks btw) , everything started working normally

Right now my `.zshrc` looks like this

```
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
```

## How can we address it?
_Configure the ANDROID_HOME environment variable_  should be updated accordingly.
Placing a sidenote in a yellow box should be enough.

## Why is it important?
I've seen a lot of people online spending hours on this

## Who needs this?
Anyone, who wants to use React Native Cli for Android

**Comment by cortinico** [comment]
This should essentially be resolved by:
- https://github.com/facebook/react-native-website/pull/2991/files

Could you verify?

**Comment by cortinico** [comment]
Closing as we removed the explicit `sdkmanager` command and there is no need to update the env variable anymore
