### ISSUE TITLE
Documentation error in @react-native/eslint-config

### ISSUE THREAD

**Issue by LcsGrz** [facebook/react-native-website#3708]
## Documentation error in @react-native/eslint-config

The error is simple, if you follow the installation steps of the eslint library it shows the following error:
```

[Error - 01:55:53] An unexpected error occurred:
[Error - 01:55:53] Error: Failed to load config "@react-native" to extend from.
Referenced from: [PROJECT]/.eslintrc.js
    at configInvalidError ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2627:9)
    at ConfigArrayFactory._loadExtendedShareableConfig ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3258:23)
    at ConfigArrayFactory._loadExtends ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3135:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3074:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2865:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3848:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile ([PROJECT]/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3769:18)
```

## Documentation version

`"@react-native-community/eslint-config": "3.2.0"` - [READ ME](https://github.com/facebook/react-native/tree/HEAD/packages/eslint-config-react-native-community#readme)

## Solution

```
{
    extends: [ '@react-native-community' ]
}
```

**Comment by cortinico** [comment]
The documentation is relative to the version on `main` which is `@react-native/eslint-config": "0.73.0"`:

https://github.com/facebook/react-native/blob/d5dad06b32ab96d70b2f6632fe99049c3dc47b55/packages/eslint-config-react-native-community/package.json#L2-L3

so it's actually correct. You're referring to a older package of ours.
