### ISSUE TITLE
Update test suite to catch 404s

### ISSUE THREAD

**Issue by hramos** [facebook/react-native-website#428]
https://github.com/facebook/react-native-website/commit/34de6d5fc0bbdd5451d8d443ffcd057fd9ffe757 brought the React Native website down because it was missing a single untracked file (`versioned_docs/version-0.5/removing-default-permissions.md`). We only deploy to React Native's `gh-pages` branch when tests run successfully, and in this commit's case, the [tests were all green](https://circleci.com/gh/facebook/react-native-website/1513).

This is not good, and we should update our Circle CI tests to catch this failure in the future.

In this specific case, the website failed to build because of a missing markdown file. The `yarn test` step actually found this issue:

```
yarn run v1.6.0
$ yarn build
$ docusaurus-build
[BABEL] Note: The code generator has deoptimised the styling of "/home/circleci/react-native-website/website/node_modules/docusaurus/lib/core/metadata.js" as it exceeds the max of "500KB".
generate.js triggered...
Site built successfully. Generated files in 'build' folder.
(node:170) UnhandledPromiseRejectionWarning: Error: Improper sidebars file for version 0.56-RC, document with id 'version-0.56-RC-removing-default-permissions' not found. Make sure that all documents with ids specified in this version's sidebar file exist and that no ids are repeated.
    at _loop (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/readCategories.js:58:17)
    at readCategories (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/readCategories.js:34:53)
    at DocsSidebar.render (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/core/DocsSidebar.js:18:26)
    at processChild (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
    at resolve (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
    at ReactDOMServerRenderer.read (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
    at renderToStaticMarkup (/home/circleci/react-native-website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2737:25)
    at renderToStaticMarkupWithDoctype (/home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/renderUtils.js:16:30)
    at /home/circleci/react-native-website/website/node_modules/docusaurus/lib/server/generate.js:199:17
(node:170) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:170) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As you can see in the error message, this is an unhandled promise rejection which did not result in a non-zero exit code. This is an issue in Docusaurus itself, but nonetheless we should protect ourselves against this in our own test suite.

**Comment by hramos** [comment]
Update: the underlying issue has been fixed in Docusaurus, https://github.com/facebook/Docusaurus/issues/805.

**Comment by hramos** [comment]
@charpeni fixed this, thanks! We'll update Docusaurus once the new release is available.
